# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2422734b83d359f533b0308b1b48e631ab303854aea64aa2813c8e309f276e4c83d4723bccee825c5d1d388ee31892b4d27c379fe4a718ada236a98f7e7945

test:
  secret_key_base: aeab64c8abc2f1b45e1ad435236791aab5a835837e6a884ded56ca5bd36c8f20598f226e87d281fbf7e87ca39af57a30587a3b44a406aee97f8a33e77d35ce6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
